### PR TITLE
Add Prometheus JMX agent to expose JVM platform jmx metrics for monitoring

### PR DESCRIPTION
**Pull request by shtirlets**
#### What type of PR is this?
Improvement

#### What does this PR do / why is it needed ?
Add Prometheus JMX agent to expose JVM platform jmx metrics for monitoring

#### Does this PR introduce a user-facing change?

Run configurations / scripts will need to be updated to activate / expose the JVM agent. See https://github.com/prometheus/jmx_exporter#running-the-java-agent for more details.

### CODE REVIEW

**Comment by gs-manvig** [comment]
Looks good to me

**Review by epsstan — CHANGES_REQUESTED** [review]
Let's take a look at how engine and the other server components expose metrics. 

I don't think they use JMX. They use a Prometheus SDK to create metrics which are then exposed via a HTTP metrics servlet/endpoint.

Can we use the same approach here ?

**Comment by shtirlets** [comment]
@epsstan we are looking to expose the JVM/Environment metrics. My understanding we are getting for free Dropwizard in other use cases.

**Review by aormerod-gs — APPROVED** [review]

**Comment by aormerod-gs** [comment]
The intention of this change is for exposing the JVM platform metrics (that are already in JMX) in to Prometheus (rather than exposing application metrics in to JMX)

**Comment by epsstan** [comment]
> The intention of this change is for exposing the JVM platform metrics (that are already in JMX) in to Prometheus (rather than exposing application metrics in to JMX)

Aah ok. My bad. I didn't read the PR carefully.  So the java agent scrapes JMX and exposes it via a HTTP server.

**Review by epsstan — APPROVED** [review]

**Pull request merged**
