### PR TITLE
Add graphFetch cross key cache tests

### PR DESCRIPTION
**Pull request by gs-ssh16**

### CODE REVIEW

**Review by pierredebelen — COMMENTED** [review]
Shouldn't we have the test in ASCII instead of JSON?

**Comment by gs-ssh16** [comment]
Hi @pierredebelen, I added the test in _legend-engine-executionPlan-execution-store-relational_ module which does not have access to parser and plan generator. Should I move it to the server module (doesn't seem to be the correct place)?

**Comment by pierredebelen** [comment]
As much as we can't have dependency to the parser & compiler in Execution's runtime & compile scope, I think it's ok to have dependencies to (legend-engine-language-pure-*) in the test scope as it will make the tests far more readable. I did the same in legend-engine-test-runner-mapping

**Comment by gs-ssh16** [comment]
Added the tests in ASCII

**Pull request merged**
