### PR TITLE
activate Reproducible Builds

### PR DESCRIPTION
**Pull request by hboutemy**
#### What type of PR is this?

enhancement: Reproducible Builds
#### What does this PR do / why is it needed ?

see https://maven.apache.org/guides/mini/guide-reproducible-builds.html

#### Which issue(s) this PR fixes:

Fixes #

### CODE REVIEW

**Comment by finos-admin** [comment]
This PR is stale because it has been open for 30 days with no activity. Please remove stale label or add any comment to keep this open. Otherwise this will be closed in 5 days.

**Comment by hboutemy** [comment]
i don't get why it keeps saying I did not sign the CLA: https://github.com/finos/open-developer-platform/pull/340

**Comment by hboutemy** [comment]
ok, let's try

**Comment by hboutemy** [comment]
new PR opened in #1216

**Pull request closed without merging**
