### PR TITLE
open source test data generation with authentication API

### PR DESCRIPTION
**Pull request by YannanGao-gs**
#### What type of PR is this?

Improvement
#### What does this PR do / why is it needed ?

open source test data generation with authentication API

https://github.com/finos/legend-engine/assets/73408381/cd906d91-67d2-4a0f-a013-7e8c1f9a831f

#### Which issue(s) this PR fixes:

Fixes #

### CODE REVIEW

**Comment by finos-admin** [comment]
This PR is stale because it has been open for 30 days with no activity. Please remove stale label or add any comment to keep this open. Otherwise this will be closed in 5 days.

**Comment by YannanGao-gs** [comment]
this pr is on hold.

**Comment by finos-admin** [comment]
This PR is stale because it has been open for 30 days with no activity. Please remove stale label or add any comment to keep this open. Otherwise this will be closed in 5 days.

**Comment by finos-admin** [comment]
This PR was closed because it has been inactive for 35 days. Please re-open if this PR is still relevant.

**Comment by YannanGao-gs** [comment]
cleaned and closed by https://github.com/finos/legend-engine/pull/3047

**Pull request closed without merging**
