### PR TITLE
Fix prepared statement params

### PR DESCRIPTION
**Pull request by shtirlets**
#### What type of PR is this?
Bug Fix

#### What does this PR do / why is it needed ?
Resolved a bug that prevented execution of prepared statements with parameters. 

#### Which issue(s) this PR fixes:

Fixes #

### CODE REVIEW

**Comment by gs-manvig** [comment]
LGTM

**Review by rafaelbey — CHANGES_REQUESTED** [review]
While the comment on test container is one to think, if we end with H2, we need to set the port to zero to avoid port collisions.

**Comment by finos-admin** [comment]
This PR is stale because it has been open for 30 days with no activity. Please remove stale label or add any comment to keep this open. Otherwise this will be closed in 5 days.

**Comment by finos-admin** [comment]
This PR was closed because it has been inactive for 35 days. Please re-open if this PR is still relevant.

**Pull request closed without merging**
