### PR TITLE
M2M feature parity: math functions

### PR DESCRIPTION
**Pull request by tanujgirdhar**
#### Which issue(s) this PR fixes:

Fixes #

### CODE REVIEW

**Comment by michalmacu** [comment]
Both mod and sqrt functions are already implemented (though were added recently to master branch). Also there is no need to add entries for a simple functions like these to Library.java (you can compare with how it's done on master branch).

**Review by AFine-gs — DISMISSED** [review]
Looks good, you will need to rebase and then can merge in.

**Comment by michalmacu** [comment]
No tests were added for stdDev

**Comment by tanujgirdhar** [comment]
> No tests were added for stdDev

javaGenerationTest has sufficient test cases for stdDev.

**Review by gs-ssh16 — APPROVED** [review]

**Pull request merged**
