### PR TITLE
Add mongo dependency and override to core config

### PR DESCRIPTION
**Pull request by hardikmaheshwari**
#### What type of PR is this?
Bug Fix

#### What does this PR do / why is it needed ?
Add mongo dependency and override to core config. This is blocking tests execution from IDE

#### Which issue(s) this PR fixes:

Fixes #

### CODE REVIEW

**Comment by rafaelbey** [comment]
I don't think this is the right solution since this create a "super" module in production, that affects downstream projects that depend on this module (and they might not need mongo).  Conceptually, this also goes against the idea that the system is modular.

To test on IDE, we need an IDE solution.  Maybe a local binder that overrides everything inside the IDE pure code?

**Comment by hardikmaheshwari** [comment]
> I don't think this is the right solution since this create a "super" module in production, that affects downstream projects that depend on this module (and they might not need mongo). Conceptually, this also goes against the idea that the system is modular.
> 
> To test on IDE, we need an IDE solution. Maybe a local binder that overrides everything inside the IDE pure code?
> 
> Otherwise, we might want to rollback the "local execution" from using this local binder and hard code java platform until a proper solution is brought that allow local binder while also respecting modularization.

@rafaelbey core-configuration module was meant to be a module aligned with server deployment and hence it is meant to be a super module which brings together dependencies for all features for a particular deployment.

**Comment by rafaelbey** [comment]
I dont agree with that design approach. If you consider all other design choices on how extensions are built, this repo just minimize if not invalidate them. 

For example, all extensions define their parsers, composers, compilers, executions, etc extensions in ways that are discovered, and everywhere we make usage of this design choice. 

This means, that with just adding these extensions as runtime dependencies on classpath, like in the Server, the process can operate with these extensions without further lines of code. 

Hence, we should solve the local binder problem in a way that, well, is actually local, while further embrace the independence of the extensions in ways that they are "plug & play". 

So, unless Im missing what value this coreconfig repo provide that the extension design does not, and Im happy to be corrected, our direction should be phase it out with solutions that work properly with the distributed design.

**Comment by ghub-real** [comment]
We don't need this anymore, do we?
(The local IDE tests need some additions - is that what we are looking to resolve?)

**Comment by finos-admin** [comment]
This PR is stale because it has been open for 30 days with no activity. Please remove stale label or add any comment to keep this open. Otherwise this will be closed in 5 days.

**Pull request closed without merging**
