### PR TITLE
Draft:Add support for new splitPart functionality.

### PR DESCRIPTION
**Pull request by vj2050gs**
#### What type of PR is this?

New Feature

#### What does this PR do / why is it needed ?

Added split_part pure function, dynaFunc, and related pure-to-SQL changes.

#### Which issue(s) this PR fixes:

Fixes #

### CODE REVIEW

**Review by vikask-gs — APPROVED** [review]

**Comment by vikask-gs** [comment]
Integration tests pass for snowflake, redshift, postgres, but fail for sqlserver

**Review by vikask-gs — CHANGES_REQUESTED** [review]
SqlServer code needs fixing

**Comment by vikask-gs** [comment]
Do we need the changes for Presto/Databricks? If not, can they be removed as we don't have adequate integration testing for them.

**Comment by finos-admin** [comment]
This PR is stale because it has been open for 30 days with no activity. Please remove stale label or add any comment to keep this open. Otherwise this will be closed in 5 days.

**Comment by finos-admin** [comment]
This PR was closed because it has been inactive for 35 days. Please re-open if this PR is still relevant.

**Pull request closed without merging**
