### PR TITLE
Add ability to generate OpenAPI spec from PureModelContext

### PR DESCRIPTION
**Pull request by kranthikiran01**
#### What type of PR is this?

Improvement
#### What does this PR do / why is it needed ?
Current openapi generation uses file generation to create openapi specification for legend service(s) inside a studio project. This file generation is invoked during builds. We need a feature to generate openapi specification on demand when pure model context is supplied. This is useful in various cases one of which is showing openapi on studio.

OpenAPIGenerationService endpoint needs to be added which addresses the above requirement.

### CODE REVIEW

**Comment by AFine-gs** [comment]
Please take a look at the  /pure/v1/external/format/generateSchema  . You may need to extend it to work with this use case.

**Comment by MauricioUyaguari** [comment]
@kranthikiran01 we shouldnt be doing this. The OpenAPI falls into the artifact generation api. We have the api already in engine. we should do the work to expose this in studio. Lets discuss this.

**Comment by finos-admin** [comment]
This PR is stale because it has been open for 30 days with no activity. Please remove stale label or add any comment to keep this open. Otherwise this will be closed in 5 days.

**Comment by finos-admin** [comment]
This PR was closed because it has been inactive for 35 days. Please re-open if this PR is still relevant.

**Pull request closed without merging**
