### PR TITLE
Unit tests for HelperMappingBuilder.convertSourceValues

### PR DESCRIPTION
**Pull request by peterschrammel**
Test all branches in `HelperMappingBuilder.convertSourceValues` and private callees as requested by @kevin-m-knight-gs.

Screenshot 2021-03-31 at 13 53 31

Tests created with the help of Diffblue Cover.

### CODE REVIEW

**Comment by peterschrammel** [comment]
> Having reviewed our contributor list, we require a CLA for the following people : (@peterschrammel).

Diffblue has got an active CLA. @finos-admin

**Comment by peterschrammel** [comment]
- CLA is approved
- Added tests pass fine: https://github.com/finos/legend-engine/pull/175/checks?check_run_id=2354329400#step:7:4638
- WhiteSource Security Check failure seems unrelated to this PR.

**Comment by finos-admin** [comment]
This PR is stale because it has been open for 30 days with no activity. Please remove stale label or add any comment to keep this open. Otherwise this will be closed in 5 days.

**Comment by finos-admin** [comment]
This PR was closed because it has been inactive for 35 days. Please re-open if this PR is still relevant.

**Pull request closed without merging**
