### PR TITLE
Fixes #1878 | Refactoring ExecutePlan#doExecutePlanLegacy()

### LINKED ISSUE #1878: RFC: Minor nits fix in ExecutePlan#doExecutePlanLegacy() implementation
### Overview

1. The method is doing too much in one go, it should be split into smaller methods for better readability and maintainability. 
2. The catch block is catching a generic Exception, which can hide potential bugs and make it harder to debug.
3. The Response object being returned in the else block should be moved to a constant for better readability and maintainability. 
4. Tracer#startActive() is deprecated. Replacing with new start() and ScopeManager.activate() implementation.

### Implementation plan

1. Split the long method into chunks of smaller private methods.
2. N/A for now till we can understand the scope of exceptions that can occur better but let's keep it in the radar.
3. Moving standard unsupported plan error response into a constant.
4. Upgrading the Tracer usage from deprecated method to new ScopeManager based implementation.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by academy-codex**
#### What does this PR do / why is it needed ?
Refactor for nits mentioned as part of Issue #1878.

#### Which issue(s) this PR fixes:

Fixes #1878

### CODE REVIEW

**Comment by academy-codex** [comment]
Any update/comments on this ?

**Comment by finos-admin** [comment]
This PR is stale because it has been open for 30 days with no activity. Please remove stale label or add any comment to keep this open. Otherwise this will be closed in 5 days.

**Comment by maoo** [comment]
Hi @academy-codex , thanks for your PR!

Unfortunately I don't have enough know-how on Legend Engine to review your PR. @akphi @epsstan @ivan-kyosev-gs - could you please review this PR ? Thanks!

**Comment by academy-codex** [comment]
I'll close this given that no response from project members.
Are external open source contributions being accepted at the moment for the project ?

**Pull request closed without merging**
